config/routes.rb
Rails.application.routes.draw do
  root "departments#index"

  resources :departments do
    resources :items
  end

  resources :items do
    resources :comments
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  before_save :check_author
  belongs_to :item

  def check_author
    if self.author.blank?
      self.author = "Anonymous"
    end
  end
end

app/models/department.rb
class Department < ApplicationRecord
  has_many :items
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :department
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_item
  def new
    @comment = Comment.new
  end

  def create
    @comment = @item.comments.new(comment_params)
    if @comment.save
      redirect_to department_item_path(@item.department_id, @item)
    else
      render :new
    end
  end

  private
    def set_item
      @item = Item.find(params[:item_id])
    end

    def comment_params
      params.require(:comment).permit(:body, :author)
    end
end

app/controllers/departments_controller.rb
class DepartmentsController < ApplicationController
before_action :set_department, only: [:show, :edit, :update, :destroy]

  def index
    @departments = Department.all
  end

  def show
  end

  def new
    @department = Department.new
    render partial: "form"
  end

  def create
    @department = Department.new(department_params)

    if @department.save
      redirect_to departments_path
    else
      render :new
    end
  end

  def edit
    render partial: "form"
  end

  def update
    if @department.update(department_params)
      redirect_to @department
    else
      render :edit
    end
  end

  def destroy
    @department.destroy
    redirect_to departments_path
  end

  private
  
  def set_department
    @department = Department.find(params[:id])
  end

  def department_params
    params.require(:department).permit(:name)
  end

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_department
  before_action :set_item, only: [:show, :edit, :update, :destroy]

  def index
    @items = @department.items
  end

  def show
  end

  def new
    @item = @department.items.new
    render partial: "form"
  end

  def create
    @item = @department.items.new(item_params)

    if @item.save
      redirect_to [@department, @item]
    else
      render :new
    end
  end

  def edit
    render partial: "form"
  end

  def update
    if @item.update(item_params)
      redirect_to [@department, @item]
    else
      render :edit
    end
  end

  def destroy
    @item.destroy
    redirect_to department_items_path
  end

  private
  def set_department
    @department = Department.find(params[:department_id])
  end

  def set_item
    @item = Item.find(params[:id])
  end

  def item_params
    params.require(:item).permit(:name, :body, :price)
  end

end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<hr />
<p>Author: <%= comment.author %></p>
<p><strong><%= comment.body %></strong></p>
</hr>

app/views/comments/new.html.erb
<h1>Add a Comment</h1>
<%= form_for [@item, @comment] do |f| %>
  <%= f.label :body %>
  <%= f.text_area :body, required: true %>
  <br />
  <%= f.label :author %>
  <%= f.text_field :author, placeholder: "Leave blank to remain anonymous" %>
  <br />
  <%= f.submit %>
<% end %>

app/views/departments/_form.html.erb
<h1><%= @department.id ? "Edit Department" : "Create Department" %></h1>
<hr />
<%= form_for @department do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name, required: true, autofocus: true %>
  <%= f.submit %>
<% end %>
<%= link_to "Back to Store", departments_path %>

app/views/departments/index.html.erb
<h1>Department Store</h1>
<%= link_to "Create a new department", new_department_path %>
<ul>
  <% @departments.each do |department| %>
    <li><%= link_to department.name, department %></li>
  <% end %>
</ul>

app/views/departments/show.html.erb
<h1><%= @department.name %></h1>
<hr />
<h4>What would you like to do?</h4>
<%= link_to "View Items", department_items_path(@department) %>
<br />
<%= link_to "Edit Department", edit_department_path(@department) %>
<br />
<%= link_to "Delete Department", @department, method: :delete %>
<br />
<%= link_to "Back to Store", departments_path %>

app/views/items/_form.html.erb
<h1><%= @item.id ? "Edit Item" : "Create Item" %></h1>
<hr />
<%= form_for [@department, @item] do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name, required: true, autofocus: true %>
  <br />
  <%= f.label :body %>
  <%= f.text_area :body, required: true %>
  <br />
  <%= f.label :price %>
  <%= f.text_field :price, required: true %>
  <br />
  <%= f.submit %>
<% end %>

app/views/items/index.html.erb
<h1><%= @department.name %> Items</h1>
<%= link_to "Create a new item", new_department_item_path(@department) %>
<ul>
  <% @items.each do |item| %>
    <li><%= link_to item.name, [@department, item] %></li>
  <% end %>
</ul>
<%= link_to "Back", department_path(@department) %>

app/views/items/show.html.erb
<h1><%= @department.name %> - <%= @item.name %></h1>
<p>Description: <%= @item.body %></p>
<p>Price: $<%= @item.price %></p>
<h2>Comments</h2>

<% @item.comments.each do |comment| %>
  <%= render "comments/comment", { comment: comment } %>
<% end %>

<hr />
<%= link_to "Add Comment", new_item_comment_path(@item) %>
<%= link_to "Edit Item", edit_department_item_path([@department, @item]) %>
<%= link_to "Delete Item", [@department, @item], method: :delete %> 
<%= link_to "Back to Deparment", department_items_path(@department) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DepartmentStore</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>